site_name: Research and Teaching IT Support
theme : 
  name: material
  custom_dir: overrides
  logo: "assets/images/UoO_Logo_RGB_Horz_Gold-REV.svg"
  favicon: "assets/images/uoo-favicon-32x32.png"
  font: 
    text: 'wickliffe-sans'
    code: 'Roboto Mono'
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
#    - navigation.expand # auto expands all sections
    - navigation.path
    - navigation.indexes
    - toc.follow



plugins:
  - search
  - awesome-nav
  - macros
  - table-reader
  - caption:
      table:
        enable: true
        caption_prefix: ''
        allow_indented_caption: false
        position: top

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions: 
  - attr_list
  - admonition
  - tables
  - footnotes
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra:
  support_email: '<a href="mailto:rtis.support@otago.ac.nz">rtis.support@otago.ac.nz</a>'
  apptainer: "/software/software_environments/self_managed/apptainer"
  nextflow: "/workflows/nextflow"
  conda: "/software/software_environments/self_managed/conda"
  spack: "/software/software_environments/self_managed/spack"
  modules: "/software/software_environments/self_managed/modules.md"
  sbgrid: "/software/software_environments/self_managed/sbgrid.md"
