ignore:
  - "child/*"
  - access/coldfront.md
nav:
  - "index.md"
  - "General":
    - general/overview.md
    - general/announcements.md
    - general/policies.md
    - general/faq.md

  - "Getting Started":
    - "getting_started/*"
  - "Access":
    - "access/*"
  - "Running Jobs":
    - "running/*"
  - "Storage":
    - "storage/*"
  - "Workflows":
    - "workflows/*"